name: "DimeNetPP"
hidden_channels: 128        
out_emb_channels: 256       
int_emb_size: 64            
basis_emb_size: 8
num_layers: 5               
cutoff: 10.0                
max_num_neighbors: 64     
num_radial: 6
envelope_exponent: 5